set_property SRC_FILE_INFO {cfile:C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/constrants.xdc rfile:../../../../constrants.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {Clk}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {Rst}]
