# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/lab8-11/.Xil/Vivado-11128-RyanDesktop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/PCAdder.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/ProgramCounter.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/PipelineReg/MemoryWriteBackReg.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/PipelineReg/DecodeExecuteReg.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/SignExtension/SignExtensionHalfByte.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux5Bit2To1.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Xor2Gate/Xor2Gate.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/SignExtension/SignExtension.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/ShiftLeft2/ShiftLeft2.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/RegisterFile/RegisterFile.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux32Bit3To1.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux32Bit2To1.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/InstructionMemory.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/HILORegisters/HILORegisters.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/PipelineReg/FetchDecodeReg.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/PipelineReg/ExecuteMemoryReg.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Controller.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/And2Gate/And2Gate.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/ALU32Bit/ALU32Bit.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Adder32/Adder32.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/DataMemory/DataMemory.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Or2Gate/Or2Gate.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/BranchController/BranchController.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/ForwardingController/ForwardingController.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/ForwardingController/HazardDetectionUnit.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/CheckEqual/IsZero.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/CheckEqual/CheckEqual.v
      D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/Processor/Processor.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Processor
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/Users/Ryan/Documents/ECE369a/lab369a/LAB8-11/DatapathComponents/lab8-11/.Xil/Vivado-11128-RyanDesktop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
