# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/PCAdder.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/ProgramCounter.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/PipelineReg/MemoryWriteBackReg.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/PipelineReg/DecodeExecuteReg.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/SignExtension/SignExtensionHalfByte.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux5Bit2To1.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Xor2Gate/Xor2Gate.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/SignExtension/SignExtension.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/ShiftLeft2/ShiftLeft2.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/RegisterFile/RegisterFile.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux32Bit3To1.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux32Bit2To1.v
  C:/Users/ryanjsims/lab369a/InstructionMemory.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/HILORegisters/HILORegisters.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/PipelineReg/FetchDecodeReg.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/PipelineReg/ExecuteMemoryReg.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Controller.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/And2Gate/And2Gate.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/ALU32Bit/ALU32Bit.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Adder32/Adder32.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/DataMemory/DataMemory.v
  C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/Processor/Processor.v
}
read_xdc C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/constrants.xdc
set_property used_in_implementation false [get_files C:/Users/ryanjsims/lab369a/LAB8-11/DatapathComponents/constrants.xdc]

synth_design -top Processor -part xc7a100tcsg324-1
write_checkpoint -noxdef Processor.dcp
catch { report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb }
