# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/lab8-11_lab/lab8-11_lab.cache/wt [current_project]
set_property parent.project_path Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/lab8-11_lab/lab8-11_lab.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/SignExtension/SignExtension.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/ShiftLeft2/ShiftLeft2.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/RegisterFile/RegisterFile.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux32Bit3To1.v
  {//vmware-host/Shared Folders/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/PipelineReg/MemoryWriteBackReg.v}
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/HILORegisters/HILORegisters.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/PipelineReg/FetchDecodeReg.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/PipelineReg/ExecuteMemoryReg.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/PipelineReg/DecodeExecuteReg.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/DataMemory/DataMemory.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/And2Gate/And2Gate.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/ALU32Bit/ALU32Bit.v
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/Adder32/Adder32.v
  {//vmware-host/Shared Folders/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/InstructionFetchUnit/ProgramCounter.v}
  {//vmware-host/Shared Folders/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/InstructionFetchUnit/PCAdder.v}
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/Mux32Bit2To1/Mux32Bit2To1.v
  {//vmware-host/Shared Folders/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/InstructionFetchUnit/InstructionMemory.v}
  Z:/Documents/2017FALL/ECE369A/lab369a/LAB8-11/DatapathComponents/Processor/Processor.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Processor -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Processor.dcp

catch { report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb }
